name: API Go Tests
permissions:
  contents: read

on:
  push:
    paths:
      - "api/**"
      - ".github/workflows/api-go-tests.yml"
  pull_request:
    branches:
      - main
      - staging

jobs:
  go-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: api/go.mod
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Run unit tests
        run: go test ./...
