{{- range $name, $svc := .Values.services }}
{{- if and ($svc.enabled | default true) ($svc.autoscaling.enabled | default false) }}
{{- $ctx := dict "root" $ "name" $name "values" $svc -}}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "api.serviceFullname" $ctx }}
  labels:
{{ include "api.serviceLabels" $ctx | nindent 4 }}
{{- $annotations := dict -}}
{{- $common := include "api.mergeAnnotations" $ctx }}
{{- if $common }}
{{- $annotations = merge $annotations ($common | fromYaml) -}}
{{- end }}
{{- with $svc.autoscaling.annotations }}
{{- $annotations = merge $annotations (deepCopy .) -}}
{{- end }}
{{- if gt (len $annotations) 0 }}
  annotations:
{{ toYaml $annotations | nindent 4 }}
{{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "api.serviceFullname" $ctx }}
  minReplicas: {{ $svc.autoscaling.minReplicas | default 2 }}
  maxReplicas: {{ $svc.autoscaling.maxReplicas | default 5 }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $svc.autoscaling.targetCPUUtilizationPercentage | default 70 }}
{{- if $svc.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $svc.autoscaling.targetMemoryUtilizationPercentage }}
{{ end }}
{{ end }}
{{- end }}
