{{- range $name, $svc := .Values.services }}
{{- if and ($svc.enabled | default true) ($svc.podDisruptionBudget.enabled | default false) }}
{{- $ctx := dict "root" $ "name" $name "values" $svc -}}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "api.serviceFullname" $ctx }}
  labels:
{{ include "api.serviceLabels" $ctx | nindent 4 }}
spec:
  selector:
    matchLabels:
{{ include "api.selectorLabels" $ctx | nindent 6 }}
{{- if $svc.podDisruptionBudget.minAvailable }}
  minAvailable: {{ $svc.podDisruptionBudget.minAvailable }}
{{- else if $svc.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ $svc.podDisruptionBudget.maxUnavailable }}
{{ end }}
{{- end }}
{{- end }}
